/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.sql.DriverManager.println;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Matheus Simoes
 */
public class TelaPrincipal extends javax.swing.JPanel implements ActionListener{
    JFrame jf=new JFrame();
    //importando as telas
    CardLayout cardLayout;
    JPanel mainPanel;
    TelaPrincipal TP;
    AddUsuario AU;
    AddRelacionamento AR;
    ListarRelacionamentos LR;
    
    public TelaPrincipal() {
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);
         TP = new TelaPrincipal();
         AU = new AddUsuario();
         AR = new AddRelacionamento();
         LR = new ListarRelacionamentos();
        mainPanel.add(TP, "telaprincipal");
        mainPanel.add(AU, "addusuario");
        mainPanel.add(AR, "addrelacionamento");
        mainPanel.add(LR, "listarrelacionamento");
        
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddUsuario = new javax.swing.JButton();
        btnListarRelacionamentos = new javax.swing.JButton();
        btnAddRelacionamento = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Miriam Libre", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simulação de Rede Social");

        jLabel2.setFont(new java.awt.Font("Miriam Libre", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teoria dos Grafos ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnAddUsuario.setBackground(new java.awt.Color(102, 153, 255));
        btnAddUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUsuario.setText("Adicionar Usuário");
        btnAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUsuarioActionPerformed(evt);
            }
        });

        btnListarRelacionamentos.setBackground(new java.awt.Color(102, 153, 255));
        btnListarRelacionamentos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnListarRelacionamentos.setForeground(new java.awt.Color(255, 255, 255));
        btnListarRelacionamentos.setText("Listar Relacionamentos");
        btnListarRelacionamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRelacionamentosActionPerformed(evt);
            }
        });

        btnAddRelacionamento.setBackground(new java.awt.Color(102, 153, 255));
        btnAddRelacionamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddRelacionamento.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRelacionamento.setText("Adicionar Relacionamento");
        btnAddRelacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRelacionamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRelacionamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarRelacionamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnAddUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddRelacionamento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarRelacionamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddUsuarioActionPerformed

    private void btnListarRelacionamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRelacionamentosActionPerformed
        // TODO add your handling code here:
        println("aaaa");
        ListarRelacionamentos lr = new ListarRelacionamentos();
        jf.getContentPane().removeAll();
        jf.getContentPane().add(lr);
    }//GEN-LAST:event_btnListarRelacionamentosActionPerformed

    private void btnAddRelacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRelacionamentoActionPerformed
        // TODO add your handling code here:
        println("aaaa");
        ListarRelacionamentos lr = new ListarRelacionamentos();
        jf.remove(this);
        jf.add(lr);
    }//GEN-LAST:event_btnAddRelacionamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRelacionamento;
    private javax.swing.JButton btnAddUsuario;
    private javax.swing.JButton btnListarRelacionamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
        //To change body of generated methods, choose Tools | Templates.
        
        
    }
}
